/* Automatic generated by './build/bin/build-entry.js' */

import FedBreadcumbs from "./fed-breadcumbs/index.js";

const components = [FedBreadcumbs];

const install = function(Vue, opts = {}) {
  /* istanbul ignore if */
  if (install.installed) return;
  components.map(component => {
    Vue.component(component.name, component);
  });
};

/* istanbul ignore if */
if (typeof window !== "undefined" && window.Vue) {
  install(window.Vue);
}

export const FedCommons = {
  install,
  FedBreadcumbs
};
